[package]
name = "ffmpegrust"
version = "1.0.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A modern, professional GUI application for video conversion and remuxing using FFmpeg"
repository = "https://github.com/yourusername/ffmpegrust"
license = "MIT"
keywords = ["ffmpeg", "video", "conversion", "gui", "multimedia"]
categories = ["multimedia::video", "gui"]
readme = "README.md"

[dependencies]
eframe = "0.24"
egui = "0.24"
rfd = "0.12"
anyhow = "1.0"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"