name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libfontconfig1-dev libasound2-dev

      - name: Check Rust version
        run: |
          rustc --version
          cargo --version

      - name: Run cargo check
        run: cargo check --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Check binary exists
        run: |
          ls -la target/release/
          file target/release/ffmpegrust

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Rust version
        run: |
          rustc --version
          cargo --version

      - name: Run cargo check
        run: cargo check --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Check binary exists
        run: |
          dir target\release\
          target\release\ffmpegrust.exe --version || echo "Binary exists but version failed"

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Check Rust version
        run: |
          rustc --version
          cargo --version

      - name: Run cargo check
        run: cargo check --verbose

      - name: Build release for Apple Silicon
        run: cargo build --release --target aarch64-apple-darwin --verbose

      - name: Check binary exists
        run: |
          ls -la target/aarch64-apple-darwin/release/
          file target/aarch64-apple-darwin/release/ffmpegrust
